### ISSUE TITLE
don't exit when you have child processes

### ISSUE THREAD

**Issue by jimdigriz** [sbyx/odhcp6c#29]
Maybe it is just me, but de-parented processes make me cry. :)

Here is a patch to make odhcp6c wait for child processes to finish before exiting:

https://github.com/jimdigriz/bratwurst/blob/master/package/odhcp6c/odhcp6c-001-wait-for-children-on-stop.patch

This lets you get from within your DHCP handling script the name of the process that called you, for example as I do in:

https://github.com/jimdigriz/bratwurst/blob/master/rootfs/usr/share/dhcpc.script

**Comment by sbyx** [comment]
I don't think that approach fits particularly well to address your issue. If you want to identify the DHCP client in the script you could easily pass an env-variable to odhcp6c when starting which is preserved in the script, e.g.

FOO=bar odhcp6c ...

and test [ "$FOO" = bar ] && ...
in your script.

I'm not exactly opposed to your approach above but to avoid casuing side-effects we should close the DHCPv6 (and ICMPv6?) socket beforehand otherwise stopping and starting odhcp6c in succession could fail in case of a longish running state-script.
